language: cpp

os: linux
env: CMAKE_BUILD_TYPE=Release
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_install:
  - yes | sudo add-apt-repository ppa:beineri/opt-qt561
  - sudo apt-get update
  - sudo apt-get install qt56base qt56tools --force-yes
  - export QTROOT=/opt/qt56

script:
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DQTROOT=${QTROOT} .
  - make