language: cpp

matrix:
  include:
    - os: linux
      env: COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Debug
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-4.9
          - g++-4.9
          - cmake
          - cmake-data

    - os: linux
      env: COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-4.9
          - g++-4.9
          - cmake
          - cmake-data

    - os: linux
      env: COMPILER=g++-5 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-5
          - g++-5
          - cmake
          - cmake-data

before_install:
  - yes | sudo add-apt-repository ppa:beineri/opt-qt561
  - sudo apt-get update
  - sudo apt-get install qt56base qt56tools --force-yes
  - export QTROOT=/opt/qt56

script:
  - CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DQTROOT=${QTROOT} .
  - make