language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Release
    - os: osx
      env: CMAKE_BUILD_TYPE=Release
      osx_image: xcode8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                                 ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                                       ; fi

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5                                     ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export QTDIR=/usr/local/Cellar/qt5/5.6.2             ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt57base qt57tools qt57xmlpatterns qt57multimedia --force-yes; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt57/bin/qt57-env.sh                   ; fi
- cmake --version

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CXX=g++-4.9 cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DQTROOT=${QTDIR} . ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DQTROOT=${QTDIR} .               ; fi
- make
- chmod +x ./.travis/deploy.sh
- source ./.travis/deploy.sh

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mK5A0dEGqx+15G9d26JqKarMuCioscx4iGZb1TqA//uv+jMvGngxcPejiC7YwhVwyFhDvBjOVPgOoUkAHS18jfdXgEqwdbFMsQY9UZyCWK3Q8GRUMuck7pV+V9FkytuCucR2N/nOymppUpvaXXjfcL56xuUsjk9iLQmvgjfgCtV+uQ7v9xUP/27ZbWcCABRKH5Q4ls9PbCDypo49Ek4ifHiScJPikbUF/osklnC2twPGyfiJL75yoMSRQPXPjUNLJoN4Nrg6wNakwFNVPA1IHwp9LiZ3wrxs+Y58sNZWfEx+zxpVyaNYuTRVFxcFOC2DBvEk8SBtqA4RLHjWU7KsSTLoKLayQK3vSVAmfRFXGbfbw4eXF5BzJoroRBnTDZyTXTh9EOixAhKAl+6nd/yaTxMhl6wgsrUYQuDhkbckCCeIIkx93UMXYWUgpeE8UuzpsO6TFxKwtq+klnDErT2T6ZAzbCylEXw4x7gln3H7vb3DG7TWvOQoALkeTNAia2ICoC+kVHZAo+lcD2e2th+eTu2G5/LiEayNYZ1DGhqMOhGRm1YeibZdqGnPnC8VVGjcpcF9kTMC+f1Uj4i5UsqsNpBCNPTB+fQaPxS3uIxPmywEtD94jM+exjJ0qGQN2NnfyZ0IudSfNnadPWoe1o70RB3+A6zShy/ya0Z2ndz8pzs=
  file: $DEPLOYFILE
  on:
    repo: coryo/amphetype2
    tags: true