language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Release

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:levi-armstrong/qt-libraries-trusty; sudo add-apt-repository -y ppa:levi-armstrong/ppa; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install qt57creator-plugin-ros; fi

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt57base qt57tools qt57xmlpatterns qt57multimedia --force-yes; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt57/bin/qt57-env.sh                   ; fi
- cmake --version

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0         ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3                      ; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CXX=g++-4.9 cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DQTROOT=${QTDIR} . ; fi
- make
- ctest -V

after_success:
- chmod +x ./.travis/deploy.sh
- source ./.travis/deploy.sh

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "mekthejacker"
      - git config --local user.email "shae.roberts@gmail.com"

deploy:
  provider: releases
  api_key:
    secure: qBv3FkHM1DPMxomEpPi6CbEKd8ODfLuC+OYwd6GhAU7mpyaQ6RvD3/gaQMbrxsDkag9Lh+6Fi6Z4jwxIGUDmywNsc7RdzRjUSyIIe96FfVI7it5HK0Q0BjlIwFeAQqcUgM6kO26qEsAPA2Wmhu9cEMd+fGh65NpOnC04E40KO4FRx0m2wrYqMeGley0B7DNRdlPzOn+LhZcUar2cwbBT9VfhrGkiJ48APy82EzUjyMNm47chF2S1n0JLMHmc4fe7bM1ZJek1/J9CcHPP7FpCbh4O6lLe0py+Q2fG1/Au64QExmPPZOJrMA7T8LbqPIOEW17NBhQQhYIHbKAYLz3frwegNvHsXQ4LiJBILCAiadsd8n1LKhx59DqE0LOmsPpfCzeu2RYjO6Y47MtCv2Ti3Bmj/wCY91YIMYpOe02/n+K6FP+jL3SOt9/6RrAK9PGHCfq5xpPbRbyH5lvh7QtK0LTRAwAKi7ptoIa/gt72sHYV3d1KkR2v7INGMM8pv01mCYIsahAmka2HuEttwWPanXZ7v7J/UuuY2tIOnqY+01VDAEFIDmcsReUNtEUm89hCtZ/Mg3TZFMSnXo2JC79HpeT5/Mki3O8L42kc6Yra8sk/74kYfbNpyMDPcuPalm78DYYZM55YqHeGqHOR0exw/5KBOU/LFpgL7VbM8tqejTQ=
  file: "$DEPLOYFILE"
  on: 
    repo: mekthejacker/amphetype2
    branch: mekthejacker-patch-test
      

